version: "3.9"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
